### ISSUE TITLE
Non-11-Digit API Keys

### ISSUE THREAD

**Issue by rheveleigh** [vga-/wave-auto-a11y#24]
I've been told that the form field for the WAVE API Key accepts only 11-digit keys (I've only ever used 11-digit keys).  Some WAVE API keys are not 11 digits.  Can the API Key form field be modified to accept keys that are not 11 digits?

**Comment by vabruzzo** [comment]
Hey Rob, this issue was fixed in the code. It's also fixed in this version of the app: http://hampshirecollege.github.io/a11yeval/index.html

Since I don't have access to hampshire.edu, I can't fix that version

All future work will have to be on the github domain. Feel free to send an email to vgabruzzo@gmail.com for any future fixes on this.

Was there ever any word from Jared about the wave api?

Hope all is well
